### ISSUE TITLE
Don`t work with laravel/framework v5.4.16  :_(

### ISSUE THREAD

**Issue by galo4kin** [assurrussa/grid-view-table#1]
Problem 1
    - Installation request for witty/laravel-table-view dev-master -> satisfiable by witty/laravel-table-view[dev-master].
    - Conclusion: remove laravel/framework v5.4.16
    - Conclusion: don't install laravel/framework v5.4.16

**Comment by assurrussa** [comment]
`composer require assurrussa/grid-view-table` ?

**Comment by galo4kin** [comment]
Прошу прощения. Ошибка была в другой зависимости – из куска копипасты это видно. Спасибо. Сейчас будем пробовать на деле.
