### ISSUE TITLE
Class amiGrid does not exist

### ISSUE THREAD

**Issue by AlexMcowkin** [assurrussa/grid-view-table#3]
Helo. Please help me
I try use your extension
`
    public function index()
    {
        $langList = $this->langService->getAll();
        $gridView = amiGrid();
        $gridView->query($langList);
        $gridView->setSearchInput(false);
`
and I get error:
Class amiGrid does not exist

**Comment by assurrussa** [comment]
@AlexMcowkin Hello, did you take all the steps correctly when installing?

**Comment by AlexMcowkin** [comment]
yes =(
