### ISSUE TITLE
clear and sorting not working

### ISSUE THREAD

**Issue by dayatfadila7** [assurrussa/grid-view-table#6]
when we clik title header sorting asc or desc not working.
click clear button not working, i use laravel 5.8.

**Comment by dayatfadila7** [comment]
solved, we must add this code

<script type="text/javascript">
window['js_amiGridList_amiGrid_1'] = new AmiGridJS({id: 'js_amiGridList_amiGrid_1', ajax: !!'true'});
</script>

**Comment by assurrussa** [comment]
Hello. Have you inserted the @stack ('scripts') `view into your template?

He should automatically connect the script.

**Comment by dayatfadila7** [comment]
i using  @stack ('js')
oh ok I will changing it from @stack ('js') to @stack ('scripts')
thank you for @assurrussa
