### ISSUE TITLE
localization not working

### ISSUE THREAD

**Issue by dayatfadila7** [assurrussa/grid-view-table#7]
hai Artur Gafurov
i how change lang in this package, i copy paste 
file grid.php from your language to lang laravel lang but not working
the result is 
- amiGrid::grid.gridCounts 
- amiGrid::grid.clear
- amiGrid::grid.filter

**Comment by assurrussa** [comment]
![image](https://user-images.githubusercontent.com/8505493/62779295-3c57ea00-bacc-11e9-8590-3e0cf4fa267a.png)

Hello, please check the correct path to the translation file.

Because everything works for me and is translated.

**Comment by dayatfadila7** [comment]
thank you @assurrussa, my bad.... missing directory vendor ,now translation  working :)
